name: Meine erste Pipeline

on:
  push:
    branches: [ main ]

jobs:
  begruessung:
    runs-on: ubuntu-latest
    steps:
      - name: Nachricht ausgeben
        run: echo "Die Pipeline laeuft!"
  html_ueberpruefen:
    runs-on: ubuntu-latest
    steps:
      - name: website Auslesen
        ansible.builtin.set_fact:
            file_content: "{{ lookup('file', 'https://github.com/hectaccomba/new_project/main/website.html') }}"
          with: actions/checkout@v4
      - name: syntax ueberpruefen
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
